owner: sehahah
repo: status

sites:
  - name: Home NAS
    url: https://test.hometraveler.org

status-website:
  baseUrl: /status
  name: HomeTraveler Status
  introTitle: "**HomeTraveler** Status"
  introMessage: Home NAS and services status
